name: deploy-hello-world
on:
  push:
    branches: [ master ]

jobs:
  update-code-on-server:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          whoami
          apt install npm -y
          apt install git -y
          git clone https://github.com/Ali-Bashir/my-app.git
          cd my-app 
          npm install
          npm run start
            
